### ISSUE TITLE
Multiidioma en etiquetas taxonomía

### ISSUE THREAD

**Issue by jbamoros** [Encamina/Enmarcha-SharePoint#12]
Hola,

Estoy usando Enmarcha en un prototipo de mis proyectos, y a la hora de aprovisionar los metadatos me es necesario aprovisionar las etiquetas de los terminos en varios idiomas, se puede realizar esta funcionalidad con la versión actual? En los ejemplos ni en el código he visto ninguna opción donde se pase el LCID.

**Comment by AdrianDiaz81** [comment]
Buenas, 
Ahora mismo en la versión de C# no esta disponible el aprovisionamiento multiidioma. 

Solamente coge el idioma en el que esta el Site. El motivo de porque no esta implementada es porque decidimos hacerlo en la versión de PowerShell que es lo que utilizamos a la hora de realizar los despliegues. Puedes ver como hacerlo aqui  https://github.com/Encamina/Enmarcha-SharePoint-PowerShell/blob/master/manual.md
