### ISSUE TITLE
bug - creating list

### ISSUE THREAD

**Issue by micuentadecasa** [Encamina/Enmarcha-SharePoint#3]
Hi, I have used the code of your sample, not your sample, I have created a classs Employed.cs and when using  var createList = web.CreateList(listName, "List of Employed of my Company", TypeList.GenericList, false, typeof(Employed));

the list that is created has two bugs:

The Name field is not created and the boss field is created as single text not as a User field

**Comment by AdrianDiaz81** [comment]
Hi Luis. 
We need to know how you implemented the Employee class so we can try to reproduce the issue. However I think you have to put the correct dataannotation or type for the User field. Can you share with us your Employee class?

**Comment by micuentadecasa** [comment]
Hi Adrian, I attach the code, is a very simple webpart, try it. I copied your code from https://github.com/Encamina/Enmarcha-SharePoint/blob/master/Samples/Enmarcha.Samples.ManageData/Model/Employed.cs without modification.

[encaminaWebpart.zip](https://github.com/Encamina/Enmarcha-SharePoint/files/165164/encaminaWebpart.zip)

**Comment by AdrianDiaz81** [comment]
Thanks Luis , reviewed the development in our farms and we say something

**Comment by AdrianDiaz81** [comment]
This bug is solved. The solution in https://github.com/Encamina/Enmarcha-SharePoint/pull/4

**Comment by micuentadecasa** [comment]
Thanks Adrian.
