### ISSUE TITLE
Using Enmarcha in console projects or not Sharepoint projects

### ISSUE THREAD

**Issue by micuentadecasa** [Encamina/Enmarcha-SharePoint#5]
Hi, I would like to know if you have tested Enmarcha in not Sharepoint projects, I mean console apps or any other type of project that is not a Sharepoint project? I need to develop some other types of projects to access information from a Sharepoint site and would like to use Enmarcha.

**Comment by AdrianDiaz81** [comment]
Hi,
In the repository there sample test or Console applications. https://github.com/Encamina/Enmarcha-SharePoint/tree/Dev/Samples 

To use Enmarcha console applications or other you must set the type of project x64 like to use the SSOM.
