### ISSUE TITLE
Bug al añadir permisos a una lista

### ISSUE THREAD

**Issue by jaiabbae** [Encamina/Enmarcha-SharePoint#6]
Hola. He detectado un bug al añadir permisos a una lista en la función AddPermissionsGroup (Enmarcha.SharePoint.Entities.Artefacts.ListSharePoint). Esta función admite como parámetros el nombre del grupo (parámetro "group") y el rol a aplicar. El problema está en cómo se obtiene la referencia al grupo:
`var oGroup = Web.Site.RootWeb.Groups.GetByName(group);`

De esta forma, si el grupo no tiene ningún permiso en el sitio raíz se produce una excepción.
Creo que la forma correcta sería la siguiente:
`var oGroup = Web.Site.RootWeb.SiteGroups.GetByName(group);`

Muchas gracias.

**Comment by AdrianDiaz81** [comment]
Buenas,

Gracias por el aporte, en principio si que parece una opción más optima la que planteas de SiteGroups y la incluiremos en la próxima actualización.

El motivo de utilizar inicialmente el Groups.GetByName era porque nos devuelve todos los grupos, sin embargo si ves la documentación lo que indica es que solamente se visualizan los grupos que tienen permiso al sitio.  https://msdn.microsoft.com/en-us/library/microsoft.sharepoint.spweb.groups.aspx 

La función SiteGroups nos devuelve todos los grupos tengan o no tengan permisos al sitio https://msdn.microsoft.com/en-us/library/microsoft.sharepoint.spweb.sitegroups.aspx
