### ISSUE TITLE
Añadir opciones de compilación

### ISSUE THREAD

**Issue by AdrianDuqueG** [Encamina/Enmarcha-SharePoint#9]
Buenas,

Sería muy interesante poder seleccionar el entorno al que te conectas cuando estás trabajando con diferentes versiones de SharePoint. De una forma similar a la siguiente:
![enmarcha](https://cloud.githubusercontent.com/assets/18736589/16581541/4d7d1c12-42aa-11e6-8448-42d3b3823a1e.png)

**Comment by AdrianDiaz81** [comment]
Con el nuevo Pull Request se añaden este requereimiento además se añade compatibilidad para SharePoint 2016 :+1:
